language: android

sudo: false

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository

before_install:
- yes | sdkmanager "platforms;android-28"