language: android

android:
  components:
    # Note that the tools section appears twice on purpose as it’s required to get the newest Android SDK tools.
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x86-android-28
    - sys-img-armeabi-v7a-android-17

before_install:
  - yes | sdkmanager "platforms;android-28"

script:
- chmod +x ./gradlew